spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/autenticador
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Autenticator-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Use o dialeto correto para MySQL
  sql:
    init:
      mode: never

server:
  port: 9997

jwt:
  secret: super-secret